version: "3.7"
services:
  php:
    build:
      context: ./.container
      args:
        VARIANT: "7"
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/*"
    volumes:
      - ./:/var/www/html
    environment:
      APP_TITLE: ï¼°ï¼¨ï¼°ã‚µãƒ³ãƒ—ãƒ«ðŸŒŸ
